using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace MovieRaterWebApp.Migrations
{
    /// <inheritdoc />
    public partial class PopulateMovieTable : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("INSERT INTO movie(Id,Title,Year,Genre,Director,Actors,Country) VALUES (1,'The Shawshank Redemption',1994,'Crime, Drama','Frank Darabont','Tim Robbins, Morgan Freeman, Bob Gunton, William Sadler','USA');");
            migrationBuilder.Sql("INSERT INTO movie(Id,Title,Year,Genre,Director,Actors,Country) VALUES (2,'The Godfather',1972,'Crime, Drama','Francis Ford Coppola','Marlon Brando, Al Pacino, James Caan, Richard S. Castellano','USA');");
            migrationBuilder.Sql("INSERT INTO movie(Id,Title,Year,Genre,Director,Actors,Country) VALUES (3,'The Godfather: Part II',1974,'Crime, Drama','Francis Ford Coppola','Al Pacino, Robert Duvall, Diane Keaton, Robert De Niro','USA');");
            migrationBuilder.Sql("INSERT INTO movie(Id,Title,Year,Genre,Director,Actors,Country) VALUES (4,'The Dark Knight',2008,'Action, Crime, Drama','Christopher Nolan','Christian Bale, Heath Ledger, Aaron Eckhart, Michael Caine','USA, UK');");
            migrationBuilder.Sql("INSERT INTO movie(Id,Title,Year,Genre,Director,Actors,Country) VALUES (5,'12 Angry Men',1957,'Crime, Drama','Sidney Lumet','Martin Balsam, John Fiedler, Lee J. Cobb, E.G. Marshall','USA');");
            migrationBuilder.Sql("INSERT INTO movie(Id,Title,Year,Genre,Director,Actors,Country) VALUES (6,'Schindler''s List',1993,'Biography, Drama, History','Steven Spielberg','Liam Neeson, Ben Kingsley, Ralph Fiennes, Caroline Goodall','USA');");
            migrationBuilder.Sql("INSERT INTO movie(Id,Title,Year,Genre,Director,Actors,Country) VALUES (7,'The Lord of the Rings: The Return of the King',2003,'Adventure, Drama, Fantasy','Peter Jackson','Noel Appleby, Ali Astin, Sean Astin, David Aston','USA, New Zealand');");
            migrationBuilder.Sql("INSERT INTO movie(Id,Title,Year,Genre,Director,Actors,Country) VALUES (8,'Pulp Fiction',1994,'Crime, Drama','Quentin Tarantino','Tim Roth, Amanda Plummer, Laura Lovelace, John Travolta','USA');");
            migrationBuilder.Sql("INSERT INTO movie(Id,Title,Year,Genre,Director,Actors,Country) VALUES (9,'Fight Club',1999,'Drama','David Fincher','Edward Norton, Brad Pitt, Meat Loaf, Zach Grenier','USA, Germany');");
            migrationBuilder.Sql("INSERT INTO movie(Id,Title,Year,Genre,Director,Actors,Country) VALUES (10,'The Lord of the Rings: The Fellowship of the Ring',2001,'Adventure, Drama, Fantasy','Peter Jackson','Alan Howard, Noel Appleby, Sean Astin, Sala Baker','New Zealand, USA');");
            migrationBuilder.Sql("INSERT INTO movie(Id,Title,Year,Genre,Director,Actors,Country) VALUES (11,'Forrest Gump',1994,'Comedy, Drama, Romance','Robert Zemeckis','Tom Hanks, Rebecca Williams, Sally Field, Michael Conner Humphreys','USA');");
            migrationBuilder.Sql("INSERT INTO movie(Id,Title,Year,Genre,Director,Actors,Country) VALUES (12,'Star Wars: Episode V - The Empire Strikes Back',1980,'Action, Adventure, Fantasy','Irvin Kershner','Mark Hamill, Harrison Ford, Carrie Fisher, Billy Dee Williams','USA');");
            migrationBuilder.Sql("INSERT INTO movie(Id,Title,Year,Genre,Director,Actors,Country) VALUES (13,'Inception',2010,'Action, Adventure, Sci-Fi','Christopher Nolan','Leonardo DiCaprio, Joseph Gordon-Levitt, Ellen Page, Tom Hardy','USA, UK');");
            migrationBuilder.Sql("INSERT INTO movie(Id,Title,Year,Genre,Director,Actors,Country) VALUES (14,'The Lord of the Rings: The Two Towers',2002,'Adventure, Drama, Fantasy','Peter Jackson','Bruce Allpress, Sean Astin, John Bach, Sala Baker','USA, New Zealand');");
            migrationBuilder.Sql("INSERT INTO movie(Id,Title,Year,Genre,Director,Actors,Country) VALUES (15,'One Flew Over the Cuckoo''s Nest',1975,'Drama','Milos Forman','Michael Berryman, Peter Brocco, Dean R. Brooks, Alonzo Brown','USA');");
            migrationBuilder.Sql("INSERT INTO movie(Id,Title,Year,Genre,Director,Actors,Country) VALUES (16,'Goodfellas',1990,'Crime, Drama','Martin Scorsese','Robert De Niro, Ray Liotta, Joe Pesci, Lorraine Bracco','USA');");
            migrationBuilder.Sql("INSERT INTO movie(Id,Title,Year,Genre,Director,Actors,Country) VALUES (17,'The Matrix',1999,'Action, Sci-Fi','Lana Wachowski, Lilly Wachowski','Keanu Reeves, Laurence Fishburne, Carrie-Anne Moss, Hugo Weaving','USA');");
            migrationBuilder.Sql("INSERT INTO movie(Id,Title,Year,Genre,Director,Actors,Country) VALUES (18,'Star Wars: Episode IV - A New Hope',1977,'Action, Adventure, Fantasy','George Lucas','Mark Hamill, Harrison Ford, Carrie Fisher, Peter Cushing','USA');");
            migrationBuilder.Sql("INSERT INTO movie(Id,Title,Year,Genre,Director,Actors,Country) VALUES (19,'Se7en',1995,'Crime, Drama, Mystery','David Fincher','Morgan Freeman, Andrew Kevin Walker, Kevin Spacey, Daniel Zacapa','USA');");
            migrationBuilder.Sql("INSERT INTO movie(Id,Title,Year,Genre,Director,Actors,Country) VALUES (20,'It''s a Wonderful Life',1946,'Drama, Family, Fantasy','Frank Capra','James Stewart, Donna Reed, Lionel Barrymore, Thomas Mitchell','USA');");
            migrationBuilder.Sql("INSERT INTO movie(Id,Title,Year,Genre,Director,Actors,Country) VALUES (21,'The Silence of the Lambs',1991,'Crime, Drama, Thriller','Jonathan Demme','Jodie Foster, Lawrence A. Bonney, Kasi Lemmons, Lawrence T. Wrentz','USA');");
            migrationBuilder.Sql("INSERT INTO movie(Id,Title,Year,Genre,Director,Actors,Country) VALUES (22,'The Usual Suspects',1995,'Crime, Drama, Mystery','Bryan Singer','Stephen Baldwin, Gabriel Byrne, Benicio Del Toro, Kevin Pollak','USA, Germany');");
            migrationBuilder.Sql("INSERT INTO movie(Id,Title,Year,Genre,Director,Actors,Country) VALUES (23,'Léon: The Professional',1994,'Crime, Drama, Thriller','Luc Besson','Jean Reno, Gary Oldman, Natalie Portman, Danny Aiello','France');");
            migrationBuilder.Sql("INSERT INTO movie(Id,Title,Year,Genre,Director,Actors,Country) VALUES (24,'Saving Private Ryan',1998,'Drama, War','Steven Spielberg','Tom Hanks, Tom Sizemore, Edward Burns, Barry Pepper','USA');");
            migrationBuilder.Sql("INSERT INTO movie(Id,Title,Year,Genre,Director,Actors,Country) VALUES (25,'City Lights',1931,'Comedy, Drama, Romance','Charles Chaplin','Virginia Cherrill, Florence Lee, Harry Myers, Al Ernest Garcia','USA');");
            migrationBuilder.Sql("INSERT INTO movie(Id,Title,Year,Genre,Director,Actors,Country) VALUES (26,'Interstellar',2014,'Adventure, Drama, Sci-Fi','Christopher Nolan','Ellen Burstyn, Matthew McConaughey, Mackenzie Foy, John Lithgow','USA, UK, Canada, Iceland');");
            migrationBuilder.Sql("INSERT INTO movie(Id,Title,Year,Genre,Director,Actors,Country) VALUES (27,'American History X',1998,'Crime, Drama','Tony Kaye','Edward Norton, Edward Furlong, Beverly D''Angelo, Jennifer Lien','USA');");
            migrationBuilder.Sql("INSERT INTO movie(Id,Title,Year,Genre,Director,Actors,Country) VALUES (28,'Modern Times',1936,'Comedy, Drama, Family','Charles Chaplin','Charles Chaplin, Paulette Goddard, Henry Bergman, Tiny Sandford','USA');");
            migrationBuilder.Sql("INSERT INTO movie(Id,Title,Year,Genre,Director,Actors,Country) VALUES (29,'Casablanca',1942,'Drama, Romance, War','Michael Curtiz','Humphrey Bogart, Ingrid Bergman, Paul Henreid, Claude Rains','USA');");
            migrationBuilder.Sql("INSERT INTO movie(Id,Title,Year,Genre,Director,Actors,Country) VALUES (30,'The Green Mile',1999,'Crime, Drama, Fantasy','Frank Darabont','Tom Hanks, David Morse, Michael Clarke Duncan, Bonnie Hunt','USA');");
            migrationBuilder.Sql("INSERT INTO movie(Id,Title,Year,Genre,Director,Actors,Country) VALUES (31,'Psycho',1960,'Horror, Mystery, Thriller','Alfred Hitchcock','Anthony Perkins, Vera Miles, John Gavin, Janet Leigh','USA');");
            migrationBuilder.Sql("INSERT INTO movie(Id,Title,Year,Genre,Director,Actors,Country) VALUES (32,'Raiders of the Lost Ark',1981,'Action, Adventure','Steven Spielberg','Harrison Ford, Karen Allen, Paul Freeman, Ronald Lacey','USA');");
            migrationBuilder.Sql("INSERT INTO movie(Id,Title,Year,Genre,Director,Actors,Country) VALUES (33,'The Pianist',2002,'Biography, Drama, Music','Roman Polanski','Adrien Brody, Emilia Fox, Michal Zebrowski, Ed Stoppard','France, Poland, Germany, UK');");
            migrationBuilder.Sql("INSERT INTO movie(Id,Title,Year,Genre,Director,Actors,Country) VALUES (34,'Rear Window',1954,'Mystery, Thriller','Alfred Hitchcock','James Stewart, Grace Kelly, Wendell Corey, Thelma Ritter','USA');");
            migrationBuilder.Sql("INSERT INTO movie(Id,Title,Year,Genre,Director,Actors,Country) VALUES (35,'The Departed',2006,'Crime, Drama, Thriller','Martin Scorsese','Leonardo DiCaprio, Matt Damon, Jack Nicholson, Mark Wahlberg','USA, Hong Kong');");
            migrationBuilder.Sql("INSERT INTO movie(Id,Title,Year,Genre,Director,Actors,Country) VALUES (36,'Whiplash',2014,'Drama, Music','Damien Chazelle','Miles Teller, J.K. Simmons, Paul Reiser, Melissa Benoist','USA');");
            migrationBuilder.Sql("INSERT INTO movie(Id,Title,Year,Genre,Director,Actors,Country) VALUES (37,'Terminator 2: Judgment Day',1991,'Action, Sci-Fi, Thriller','James Cameron','Arnold Schwarzenegger, Linda Hamilton, Edward Furlong, Robert Patrick','USA, France');");
            migrationBuilder.Sql("INSERT INTO movie(Id,Title,Year,Genre,Director,Actors,Country) VALUES (38,'Back to the Future',1985,'Adventure, Comedy, Sci-Fi','Robert Zemeckis','Michael J. Fox, Christopher Lloyd, Lea Thompson, Crispin Glover','USA');");
            migrationBuilder.Sql("INSERT INTO movie(Id,Title,Year,Genre,Director,Actors,Country) VALUES (39,'Gladiator',2000,'Action, Adventure, Drama','Ridley Scott','Russell Crowe, Joaquin Phoenix, Connie Nielsen, Oliver Reed','USA, UK');");
            migrationBuilder.Sql("INSERT INTO movie(Id,Title,Year,Genre,Director,Actors,Country) VALUES (40,'The Lion King',1994,'Animation, Adventure, Drama','Roger Allers, Rob Minkoff','Rowan Atkinson, Matthew Broderick, Niketa Calame, Jim Cummings','USA');");
            migrationBuilder.Sql("INSERT INTO movie(Id,Title,Year,Genre,Director,Actors,Country) VALUES (41,'The Prestige',2006,'Drama, Mystery, Sci-Fi','Christopher Nolan','Hugh Jackman, Christian Bale, Michael Caine, Piper Perabo','USA, UK');");
            migrationBuilder.Sql("INSERT INTO movie(Id,Title,Year,Genre,Director,Actors,Country) VALUES (42,'Apocalypse Now',1979,'Drama, War','Francis Ford Coppola','Marlon Brando, Martin Sheen, Robert Duvall, Frederic Forrest','USA');");
            migrationBuilder.Sql("INSERT INTO movie(Id,Title,Year,Genre,Director,Actors,Country) VALUES (43,'Memento',2000,'Mystery, Thriller','Christopher Nolan','Guy Pearce, Carrie-Anne Moss, Joe Pantoliano, Mark Boone Junior','USA');");
            migrationBuilder.Sql("INSERT INTO movie(Id,Title,Year,Genre,Director,Actors,Country) VALUES (44,'The Great Dictator',1940,'Comedy, Drama, War','Charles Chaplin','Charles Chaplin, Jack Oakie, Reginald Gardiner, Henry Daniell','USA');");
            migrationBuilder.Sql("INSERT INTO movie(Id,Title,Year,Genre,Director,Actors,Country) VALUES (45,'Sunset Boulevard',1950,'Drama, Film-Noir','Billy Wilder','William Holden, Gloria Swanson, Erich von Stroheim, Nancy Olson','USA');");
            migrationBuilder.Sql("INSERT INTO movie(Id,Title,Year,Genre,Director,Actors,Country) VALUES (46,'Alien',1979,'Horror, Sci-Fi','Ridley Scott','Tom Skerritt, Sigourney Weaver, Veronica Cartwright, Harry Dean Stanton','UK, USA');");
            migrationBuilder.Sql("INSERT INTO movie(Id,Title,Year,Genre,Director,Actors,Country) VALUES (47,'Dr. Strangelove or: How I Learned to Stop Worrying and Love the Bomb',1964,'Comedy','Stanley Kubrick','Peter Sellers, George C. Scott, Sterling Hayden, Keenan Wynn','USA, UK');");
            migrationBuilder.Sql("INSERT INTO movie(Id,Title,Year,Genre,Director,Actors,Country) VALUES (48,'Paths of Glory',1957,'Drama, War','Stanley Kubrick','Kirk Douglas, Ralph Meeker, Adolphe Menjou, George Macready','USA');");
            migrationBuilder.Sql("INSERT INTO movie(Id,Title,Year,Genre,Director,Actors,Country) VALUES (49,'Django Unchained',2012,'Drama, Western','Quentin Tarantino','Jamie Foxx, Christoph Waltz, Leonardo DiCaprio, Kerry Washington','USA');");
            migrationBuilder.Sql("INSERT INTO movie(Id,Title,Year,Genre,Director,Actors,Country) VALUES (50,'The Shining',1980,'Drama, Horror','Stanley Kubrick','Jack Nicholson, Shelley Duvall, Danny Lloyd, Scatman Crothers','UK, USA');");
            migrationBuilder.Sql("INSERT INTO movie(Id,Title,Year,Genre,Director,Actors,Country) VALUES (51,'Witness for the Prosecution',1957,'Crime, Drama, Mystery','Billy Wilder','Tyrone Power, Marlene Dietrich, Charles Laughton, Elsa Lanchester','USA');");
            migrationBuilder.Sql("INSERT INTO movie(Id,Title,Year,Genre,Director,Actors,Country) VALUES (52,'The Dark Knight Rises',2012,'Action, Thriller','Christopher Nolan','Christian Bale, Gary Oldman, Tom Hardy, Joseph Gordon-Levitt','UK, USA');");
            migrationBuilder.Sql("INSERT INTO movie(Id,Title,Year,Genre,Director,Actors,Country) VALUES (53,'WALL·E',2008,'Animation, Adventure, Family','Andrew Stanton','Ben Burtt, Elissa Knight, Jeff Garlin, Fred Willard','USA');");
            migrationBuilder.Sql("INSERT INTO movie(Id,Title,Year,Genre,Director,Actors,Country) VALUES (54,'American Beauty',1999,'Drama, Romance','Sam Mendes','Kevin Spacey, Annette Bening, Thora Birch, Wes Bentley','USA');");
            migrationBuilder.Sql("INSERT INTO movie(Id,Title,Year,Genre,Director,Actors,Country) VALUES (55,'Once Upon a Time in America',1984,'Crime, Drama','Sergio Leone','Robert De Niro, James Woods, Elizabeth McGovern, Joe Pesci','Italy, USA');");
            migrationBuilder.Sql("INSERT INTO movie(Id,Title,Year,Genre,Director,Actors,Country) VALUES (56,'Aliens',1986,'Action, Adventure, Sci-Fi','James Cameron','Sigourney Weaver, Carrie Henn, Michael Biehn, Paul Reiser','USA, UK');");
            migrationBuilder.Sql("INSERT INTO movie(Id,Title,Year,Genre,Director,Actors,Country) VALUES (57,'Citizen Kane',1941,'Drama, Mystery','Orson Welles','Joseph Cotten, Dorothy Comingore, Agnes Moorehead, Ruth Warrick','USA');");
            migrationBuilder.Sql("INSERT INTO movie(Id,Title,Year,Genre,Director,Actors,Country) VALUES (58,'North by Northwest',1959,'Action, Adventure, Mystery','Alfred Hitchcock','Cary Grant, Eva Marie Saint, James Mason, Jessie Royce Landis','USA');");
            migrationBuilder.Sql("INSERT INTO movie(Id,Title,Year,Genre,Director,Actors,Country) VALUES (59,'Vertigo',1958,'Mystery, Romance, Thriller','Alfred Hitchcock','James Stewart, Kim Novak, Barbara Bel Geddes, Tom Helmore','USA');");
            migrationBuilder.Sql("INSERT INTO movie(Id,Title,Year,Genre,Director,Actors,Country) VALUES (60,'Star Wars: Episode VI - Return of the Jedi',1983,'Action, Adventure, Fantasy','Richard Marquand','Mark Hamill, Harrison Ford, Carrie Fisher, Billy Dee Williams','USA');");
            migrationBuilder.Sql("INSERT INTO movie(Id,Title,Year,Genre,Director,Actors,Country) VALUES (61,'Braveheart',1995,'Biography, Drama, History','Mel Gibson','James Robinson, Sean Lawlor, Sandy Nelson, James Cosmo','USA');");
            migrationBuilder.Sql("INSERT INTO movie(Id,Title,Year,Genre,Director,Actors,Country) VALUES (62,'Reservoir Dogs',1992,'Crime, Drama, Thriller','Quentin Tarantino','Harvey Keitel, Tim Roth, Michael Madsen, Chris Penn','USA');");
            migrationBuilder.Sql("INSERT INTO movie(Id,Title,Year,Genre,Director,Actors,Country) VALUES (63,'Double Indemnity',1944,'Crime, Drama, Film-Noir','Billy Wilder','Fred MacMurray, Barbara Stanwyck, Edward G. Robinson, Porter Hall','USA');");
            migrationBuilder.Sql("INSERT INTO movie(Id,Title,Year,Genre,Director,Actors,Country) VALUES (64,'Requiem for a Dream',2000,'Drama','Darren Aronofsky','Ellen Burstyn, Jared Leto, Jennifer Connelly, Marlon Wayans','USA');");
            migrationBuilder.Sql("INSERT INTO movie(Id,Title,Year,Genre,Director,Actors,Country) VALUES (65,'Lawrence of Arabia',1962,'Adventure, Biography, Drama','David Lean','Peter O''Toole, Alec Guinness, Anthony Quinn, Jack Hawkins','UK, USA');");
            migrationBuilder.Sql("INSERT INTO movie(Id,Title,Year,Genre,Director,Actors,Country) VALUES (66,'The Kid',1921,'Comedy, Drama, Family','Charles Chaplin','Carl Miller, Edna Purviance, Jackie Coogan, Charles Chaplin','USA');");
            migrationBuilder.Sql("INSERT INTO movie(Id,Title,Year,Genre,Director,Actors,Country) VALUES (67,'A Clockwork Orange',1971,'Crime, Drama, Sci-Fi','Stanley Kubrick','Malcolm McDowell, Patrick Magee, Michael Bates, Warren Clarke','UK, USA');");
            migrationBuilder.Sql("INSERT INTO movie(Id,Title,Year,Genre,Director,Actors,Country) VALUES (68,'Amadeus',1984,'Biography, Drama, History','Milos Forman','F. Murray Abraham, Tom Hulce, Elizabeth Berridge, Roy Dotrice','USA, France');");
            migrationBuilder.Sql("INSERT INTO movie(Id,Title,Year,Genre,Director,Actors,Country) VALUES (69,'To Kill a Mockingbird',1962,'Crime, Drama','Robert Mulligan','Gregory Peck, John Megna, Frank Overton, Rosemary Murphy','USA');");
            migrationBuilder.Sql("INSERT INTO movie(Id,Title,Year,Genre,Director,Actors,Country) VALUES (70,'Eternal Sunshine of the Spotless Mind',2004,'Drama, Romance, Sci-Fi','Michel Gondry','Jim Carrey, Kate Winslet, Gerry Robert Byrne, Elijah Wood','USA');");
            migrationBuilder.Sql("INSERT INTO movie(Id,Title,Year,Genre,Director,Actors,Country) VALUES (71,'Singin'' in the Rain',1952,'Comedy, Musical, Romance','Stanley Donen, Gene Kelly','Gene Kelly, Donald O''Connor, Debbie Reynolds, Jean Hagen','USA');");
            migrationBuilder.Sql("INSERT INTO movie(Id,Title,Year,Genre,Director,Actors,Country) VALUES (72,'Taxi Driver',1976,'Crime, Drama','Martin Scorsese','Diahnne Abbott, Frank Adu, Victor Argo, Gino Ardito','USA');");
            migrationBuilder.Sql("INSERT INTO movie(Id,Title,Year,Genre,Director,Actors,Country) VALUES (73,'The Sting',1973,'Comedy, Crime, Drama','George Roy Hill','Paul Newman, Robert Redford, Robert Shaw, Charles Durning','USA');");
            migrationBuilder.Sql("INSERT INTO movie(Id,Title,Year,Genre,Director,Actors,Country) VALUES (74,'Toy Story 3',2010,'Animation, Adventure, Comedy','Lee Unkrich','Tom Hanks, Tim Allen, Joan Cusack, Ned Beatty','USA');");
            migrationBuilder.Sql("INSERT INTO movie(Id,Title,Year,Genre,Director,Actors,Country) VALUES (75,'2001: A Space Odyssey',1968,'Adventure, Sci-Fi','Stanley Kubrick','Keir Dullea, Gary Lockwood, William Sylvester, Daniel Richter','UK, USA');");
            migrationBuilder.Sql("INSERT INTO movie(Id,Title,Year,Genre,Director,Actors,Country) VALUES (76,'Full Metal Jacket',1987,'Drama, War','Stanley Kubrick','Matthew Modine, Adam Baldwin, Vincent D''Onofrio, R. Lee Ermey','UK, USA');");
            migrationBuilder.Sql("INSERT INTO movie(Id,Title,Year,Genre,Director,Actors,Country) VALUES (77,'Baby Driver',2017,'Action, Crime, Music','Edgar Wright','Ansel Elgort, Jon Bernthal, Jon Hamm, Eiza González','UK, USA');");
            migrationBuilder.Sql("INSERT INTO movie(Id,Title,Year,Genre,Director,Actors,Country) VALUES (78,'Toy Story',1995,'Animation, Adventure, Comedy','John Lasseter','Tom Hanks, Tim Allen, Don Rickles, Jim Varney','USA');");
            migrationBuilder.Sql("INSERT INTO movie(Id,Title,Year,Genre,Director,Actors,Country) VALUES (79,'Inglourious Basterds',2009,'Adventure, Drama, War','Quentin Tarantino, Eli Roth','Brad Pitt, Mélanie Laurent, Christoph Waltz, Eli Roth','USA, Germany');");
            migrationBuilder.Sql("INSERT INTO movie(Id,Title,Year,Genre,Director,Actors,Country) VALUES (80,'Snatch',2000,'Comedy, Crime','Guy Ritchie','Benicio Del Toro, Dennis Farina, Vinnie Jones, Brad Pitt','UK, USA');");
            migrationBuilder.Sql("INSERT INTO movie(Id,Title,Year,Genre,Director,Actors,Country) VALUES (81,'The Apartment',1960,'Comedy, Drama, Romance','Billy Wilder','Jack Lemmon, Shirley MacLaine, Fred MacMurray, Ray Walston','USA');");
            migrationBuilder.Sql("INSERT INTO movie(Id,Title,Year,Genre,Director,Actors,Country) VALUES (82,'All About Eve',1950,'Drama','Joseph L. Mankiewicz','Bette Davis, Anne Baxter, George Sanders, Celeste Holm','USA');");
            migrationBuilder.Sql("INSERT INTO movie(Id,Title,Year,Genre,Director,Actors,Country) VALUES (83,'Monty Python and the Holy Grail',1975,'Adventure, Comedy, Fantasy','Terry Gilliam, Terry Jones','Graham Chapman, John Cleese, Eric Idle, Terry Gilliam','UK');");
            migrationBuilder.Sql("INSERT INTO movie(Id,Title,Year,Genre,Director,Actors,Country) VALUES (84,'Scarface',1983,'Crime, Drama','Brian De Palma','Al Pacino, Steven Bauer, Michelle Pfeiffer, Mary Elizabeth Mastrantonio','USA');");
            migrationBuilder.Sql("INSERT INTO movie(Id,Title,Year,Genre,Director,Actors,Country) VALUES (85,'L.A. Confidential',1997,'Crime, Drama, Mystery','Curtis Hanson','Kevin Spacey, Russell Crowe, Guy Pearce, James Cromwell','USA');");
            migrationBuilder.Sql("INSERT INTO movie(Id,Title,Year,Genre,Director,Actors,Country) VALUES (86,'Good Will Hunting',1997,'Drama','Gus Van Sant','Matt Damon, Ben Affleck, Stellan Skarsgård, John Mighton','USA');");
            migrationBuilder.Sql("INSERT INTO movie(Id,Title,Year,Genre,Director,Actors,Country) VALUES (87,'The Treasure of the Sierra Madre',1948,'Adventure, Drama, Western','John Huston','Humphrey Bogart, Walter Huston, Tim Holt, Bruce Bennett','USA');");
            migrationBuilder.Sql("INSERT INTO movie(Id,Title,Year,Genre,Director,Actors,Country) VALUES (88,'Indiana Jones and the Last Crusade',1989,'Action, Adventure, Fantasy','Steven Spielberg','Harrison Ford, Sean Connery, Denholm Elliott, Alison Doody','USA');");
            migrationBuilder.Sql("INSERT INTO movie(Id,Title,Year,Genre,Director,Actors,Country) VALUES (89,'Some Like It Hot',1959,'Comedy, Romance','Billy Wilder','Marilyn Monroe, Tony Curtis, Jack Lemmon, George Raft','USA');");
            migrationBuilder.Sql("INSERT INTO movie(Id,Title,Year,Genre,Director,Actors,Country) VALUES (90,'Batman Begins',2005,'Action, Adventure','Christopher Nolan','Christian Bale, Michael Caine, Liam Neeson, Katie Holmes','USA, UK');");
            migrationBuilder.Sql("INSERT INTO movie(Id,Title,Year,Genre,Director,Actors,Country) VALUES (91,'Up',2009,'Animation, Adventure, Comedy','Pete Docter, Bob Peterson','Edward Asner, Christopher Plummer, Jordan Nagai, Bob Peterson','USA');");
            migrationBuilder.Sql("INSERT INTO movie(Id,Title,Year,Genre,Director,Actors,Country) VALUES (92,'The Third Man',1949,'Film-Noir, Mystery, Thriller','Carol Reed','Joseph Cotten, Alida Valli, Orson Welles, Trevor Howard','UK');");
            migrationBuilder.Sql("INSERT INTO movie(Id,Title,Year,Genre,Director,Actors,Country) VALUES (93,'Unforgiven',1992,'Drama, Western','Clint Eastwood','Clint Eastwood, Gene Hackman, Morgan Freeman, Richard Harris','USA');");
            migrationBuilder.Sql("INSERT INTO movie(Id,Title,Year,Genre,Director,Actors,Country) VALUES (94,'Judgment at Nuremberg',1961,'Drama, War','Stanley Kramer','Spencer Tracy, Burt Lancaster, Richard Widmark, Marlene Dietrich','USA');");
            migrationBuilder.Sql("INSERT INTO movie(Id,Title,Year,Genre,Director,Actors,Country) VALUES (95,'Raging Bull',1980,'Biography, Drama, Sport','Martin Scorsese','Robert De Niro, Cathy Moriarty, Joe Pesci, Frank Vincent','USA');");
            migrationBuilder.Sql("INSERT INTO movie(Id,Title,Year,Genre,Director,Actors,Country) VALUES (96,'The Great Escape',1963,'Adventure, Drama, History','John Sturges','Steve McQueen, James Garner, Richard Attenborough, James Donald','USA');");
            migrationBuilder.Sql("INSERT INTO movie(Id,Title,Year,Genre,Director,Actors,Country) VALUES (97,'Heat',1995,'Action, Crime, Drama','Michael Mann','Al Pacino, Robert De Niro, Val Kilmer, Jon Voight','USA');");
            migrationBuilder.Sql("INSERT INTO movie(Id,Title,Year,Genre,Director,Actors,Country) VALUES (98,'Die Hard',1988,'Action, Thriller','John McTiernan','Bruce Willis, Bonnie Bedelia, Reginald VelJohnson, Paul Gleason','USA');");
            migrationBuilder.Sql("INSERT INTO movie(Id,Title,Year,Genre,Director,Actors,Country) VALUES (99,'The Gold Rush',1925,'Adventure, Comedy, Drama','Charles Chaplin','Charles Chaplin, Mack Swain, Tom Murray, Henry Bergman','USA');");
            migrationBuilder.Sql("INSERT INTO movie(Id,Title,Year,Genre,Director,Actors,Country) VALUES (100,'Chinatown',1974,'Drama, Mystery, Thriller','Roman Polanski','Jack Nicholson, Faye Dunaway, John Huston, Perry Lopez','USA');");
            migrationBuilder.Sql("INSERT INTO movie(Id,Title,Year,Genre,Director,Actors,Country) VALUES (101,'On the Waterfront',1954,'Crime, Drama, Thriller','Elia Kazan','Marlon Brando, Karl Malden, Lee J. Cobb, Rod Steiger','USA');");
            migrationBuilder.Sql("INSERT INTO movie(Id,Title,Year,Genre,Director,Actors,Country) VALUES (102,'Mr. Smith Goes to Washington',1939,'Comedy, Drama','Frank Capra','Jean Arthur, James Stewart, Claude Rains, Edward Arnold','USA');");
            migrationBuilder.Sql("INSERT INTO movie(Id,Title,Year,Genre,Director,Actors,Country) VALUES (103,'The General',1926,'Action, Adventure, Comedy','Clyde Bruckman, Buster Keaton','Buster Keaton, Marion Mack, Glen Cavender, Jim Farley','USA');");
            migrationBuilder.Sql("INSERT INTO movie(Id,Title,Year,Genre,Director,Actors,Country) VALUES (104,'Inside Out',2015,'Animation, Adventure, Comedy','Pete Docter, Ronnie Del Carmen','Amy Poehler, Phyllis Smith, Richard Kind, Bill Hader','USA');");
            migrationBuilder.Sql("INSERT INTO movie(Id,Title,Year,Genre,Director,Actors,Country) VALUES (105,'The Bridge on the River Kwai',1957,'Adventure, Drama, War','David Lean','William Holden, Alec Guinness, Jack Hawkins, Sessue Hayakawa','UK, USA');");
            migrationBuilder.Sql("INSERT INTO movie(Id,Title,Year,Genre,Director,Actors,Country) VALUES (106,'Room',2015,'Drama','Lenny Abrahamson','Brie Larson, Jacob Tremblay, Sean Bridgers, Wendy Crewson','Ireland, Canada, UK, USA');");
            migrationBuilder.Sql("INSERT INTO movie(Id,Title,Year,Genre,Director,Actors,Country) VALUES (107,'La La Land',2016,'Comedy, Drama, Music','Damien Chazelle','Ryan Gosling, Emma Stone, Amiée Conn, Terry Walters','USA');");
            migrationBuilder.Sql("INSERT INTO movie(Id,Title,Year,Genre,Director,Actors,Country) VALUES (108,'Logan',2017,'Action, Drama, Sci-Fi','James Mangold','Hugh Jackman, Patrick Stewart, Dafne Keen, Boyd Holbrook','USA, Canada, Australia');");
            migrationBuilder.Sql("INSERT INTO movie(Id,Title,Year,Genre,Director,Actors,Country) VALUES (109,'Blade Runner',1982,'Sci-Fi, Thriller','Ridley Scott','Harrison Ford, Rutger Hauer, Sean Young, Edward James Olmos','USA, Hong Kong, UK');");
            migrationBuilder.Sql("INSERT INTO movie(Id,Title,Year,Genre,Director,Actors,Country) VALUES (110,'Lock, Stock and Two Smoking Barrels',1998,'Comedy, Crime','Guy Ritchie','Jason Flemyng, Dexter Fletcher, Nick Moran, Jason Statham','UK');");
            migrationBuilder.Sql("INSERT INTO movie(Id,Title,Year,Genre,Director,Actors,Country) VALUES (111,'Casino',1995,'Crime, Drama','Martin Scorsese','Robert De Niro, Sharon Stone, Joe Pesci, James Woods','France, USA');");
            migrationBuilder.Sql("INSERT INTO movie(Id,Title,Year,Genre,Director,Actors,Country) VALUES (112,'A Beautiful Mind',2001,'Biography, Drama','Ron Howard','Russell Crowe, Ed Harris, Jennifer Connelly, Christopher Plummer','USA');");
            migrationBuilder.Sql("INSERT INTO movie(Id,Title,Year,Genre,Director,Actors,Country) VALUES (113,'The Elephant Man',1980,'Biography, Drama','David Lynch','Anthony Hopkins, John Hurt, Anne Bancroft, John Gielgud','USA, UK');");
            migrationBuilder.Sql("INSERT INTO movie(Id,Title,Year,Genre,Director,Actors,Country) VALUES (114,'Warrior',2011,'Action, Drama, Sport','Gavin O''Connor','Joel Edgerton, Tom Hardy, Nick Nolte, Jennifer Morrison','USA');");
            migrationBuilder.Sql("INSERT INTO movie(Id,Title,Year,Genre,Director,Actors,Country) VALUES (115,'V for Vendetta',2005,'Action, Drama, Thriller','James McTeigue','Natalie Portman, Hugo Weaving, Stephen Rea, Stephen Fry','USA, UK, Germany');");
            migrationBuilder.Sql("INSERT INTO movie(Id,Title,Year,Genre,Director,Actors,Country) VALUES (116,'The Wolf of Wall Street',2013,'Biography, Comedy, Crime','Martin Scorsese','Leonardo DiCaprio, Jonah Hill, Margot Robbie, Matthew McConaughey','USA');");
            migrationBuilder.Sql("INSERT INTO movie(Id,Title,Year,Genre,Director,Actors,Country) VALUES (117,'Dial M for Murder',1954,'Crime, Film-Noir, Thriller','Alfred Hitchcock','Ray Milland, Grace Kelly, Robert Cummings, John Williams','USA');");
            migrationBuilder.Sql("INSERT INTO movie(Id,Title,Year,Genre,Director,Actors,Country) VALUES (118,'Hacksaw Ridge',2016,'Biography, Drama, History','Mel Gibson','Andrew Garfield, Richard Pyros, Jacob Warner, Milo Gibson','Australia, USA');");
            migrationBuilder.Sql("INSERT INTO movie(Id,Title,Year,Genre,Director,Actors,Country) VALUES (119,'Gone with the Wind',1939,'Drama, History, Romance','Victor Fleming, George Cukor, Sam Wood','Thomas Mitchell, Barbara O''Neil, Vivien Leigh, Evelyn Keyes','USA');");
            migrationBuilder.Sql("INSERT INTO movie(Id,Title,Year,Genre,Director,Actors,Country) VALUES (120,'The Message',1976,'Adventure, Biography, Drama','Moustapha Akkad','Anthony Quinn, Irene Papas, Michael Ansara, Johnny Sekka','Lebanon, Libya, Kuwait, Morocco, UK');");
            migrationBuilder.Sql("INSERT INTO movie(Id,Title,Year,Genre,Director,Actors,Country) VALUES (121,'Rebecca',1940,'Drama, Mystery, Romance','Alfred Hitchcock','Laurence Olivier, Joan Fontaine, George Sanders, Judith Anderson','USA');");
            migrationBuilder.Sql("INSERT INTO movie(Id,Title,Year,Genre,Director,Actors,Country) VALUES (122,'Trainspotting',1996,'Drama','Danny Boyle','Ewan McGregor, Ewen Bremner, Jonny Lee Miller, Kevin McKidd','UK');");
            migrationBuilder.Sql("INSERT INTO movie(Id,Title,Year,Genre,Director,Actors,Country) VALUES (123,'The Deer Hunter',1978,'Drama, War','Michael Cimino','Robert De Niro, John Cazale, John Savage, Christopher Walken','USA, UK');");
            migrationBuilder.Sql("INSERT INTO movie(Id,Title,Year,Genre,Director,Actors,Country) VALUES (124,'Cool Hand Luke',1967,'Crime, Drama','Stuart Rosenberg','Paul Newman, George Kennedy, J.D. Cannon, Lou Antonio','USA');");
            migrationBuilder.Sql("INSERT INTO movie(Id,Title,Year,Genre,Director,Actors,Country) VALUES (125,'Gran Torino',2008,'Drama','Clint Eastwood','Clint Eastwood, Christopher Carley, Bee Vang, Ahney Her','Germany, USA');");
            migrationBuilder.Sql("INSERT INTO movie(Id,Title,Year,Genre,Director,Actors,Country) VALUES (126,'The Big Lebowski',1998,'Comedy, Crime','Joel Coen, Ethan Coen','Jeff Bridges, John Goodman, Julianne Moore, Steve Buscemi','USA, UK');");
            migrationBuilder.Sql("INSERT INTO movie(Id,Title,Year,Genre,Director,Actors,Country) VALUES (127,'The Thing',1982,'Horror, Mystery, Sci-Fi','John Carpenter','Kurt Russell, Wilford Brimley, T.K. Carter, David Clennon','USA');");
            migrationBuilder.Sql("INSERT INTO movie(Id,Title,Year,Genre,Director,Actors,Country) VALUES (128,'It Happened One Night',1934,'Comedy, Romance','Frank Capra','Clark Gable, Claudette Colbert, Walter Connolly, Roscoe Karns','USA');");
            migrationBuilder.Sql("INSERT INTO movie(Id,Title,Year,Genre,Director,Actors,Country) VALUES (129,'Fargo',1996,'Crime, Drama, Thriller','Joel Coen, Ethan Coen','William H. Macy, Steve Buscemi, Peter Stormare, Kristin Rudrüd','USA, UK');");
            migrationBuilder.Sql("INSERT INTO movie(Id,Title,Year,Genre,Director,Actors,Country) VALUES (130,'The Sixth Sense',1999,'Drama, Mystery, Thriller','M. Night Shyamalan','Bruce Willis, Haley Joel Osment, Toni Collette, Olivia Williams','USA');");
            migrationBuilder.Sql("INSERT INTO movie(Id,Title,Year,Genre,Director,Actors,Country) VALUES (131,'Finding Nemo',2003,'Animation, Adventure, Comedy','Andrew Stanton, Lee Unkrich','Albert Brooks, Ellen DeGeneres, Alexander Gould, Willem Dafoe','USA');");
            migrationBuilder.Sql("INSERT INTO movie(Id,Title,Year,Genre,Director,Actors,Country) VALUES (132,'Mary and Max',2009,'Animation, Comedy, Drama','Adam Elliot','Toni Collette, Philip Seymour Hoffman, Barry Humphries, Eric Bana','Australia');");
            migrationBuilder.Sql("INSERT INTO movie(Id,Title,Year,Genre,Director,Actors,Country) VALUES (133,'No Country for Old Men',2007,'Crime, Drama, Thriller','Ethan Coen, Joel Coen','Tommy Lee Jones, Javier Bardem, Josh Brolin, Woody Harrelson','USA');");
            migrationBuilder.Sql("INSERT INTO movie(Id,Title,Year,Genre,Director,Actors,Country) VALUES (134,'How to Train Your Dragon',2010,'Animation, Action, Adventure','Dean DeBlois, Chris Sanders','Jay Baruchel, Gerard Butler, Craig Ferguson, America Ferrera','USA');");
            migrationBuilder.Sql("INSERT INTO movie(Id,Title,Year,Genre,Director,Actors,Country) VALUES (135,'There Will Be Blood',2007,'Drama, History','Paul Thomas Anderson','Daniel Day-Lewis, Martin Stringer, Matthew Braden Stringer, Jacob Stringer','USA');");
            migrationBuilder.Sql("INSERT INTO movie(Id,Title,Year,Genre,Director,Actors,Country) VALUES (136,'Into the Wild',2007,'Adventure, Biography, Drama','Sean Penn','Emile Hirsch, Marcia Gay Harden, William Hurt, Jena Malone','USA');");
            migrationBuilder.Sql("INSERT INTO movie(Id,Title,Year,Genre,Director,Actors,Country) VALUES (137,'Kill Bill: Vol. 1',2003,'Action, Crime, Thriller','Quentin Tarantino','Uma Thurman, Lucy Liu, Vivica A. Fox, Daryl Hannah','USA');");
            migrationBuilder.Sql("INSERT INTO movie(Id,Title,Year,Genre,Director,Actors,Country) VALUES (138,'Gone Girl',2014,'Crime, Drama, Mystery','David Fincher','Ben Affleck, Rosamund Pike, Neil Patrick Harris, Tyler Perry','USA');");
            migrationBuilder.Sql("INSERT INTO movie(Id,Title,Year,Genre,Director,Actors,Country) VALUES (139,'Life of Brian',1979,'Comedy','Terry Jones','Graham Chapman, John Cleese, Terry Gilliam, Eric Idle','UK');");
            migrationBuilder.Sql("INSERT INTO movie(Id,Title,Year,Genre,Director,Actors,Country) VALUES (140,'Network',1976,'Drama','Sidney Lumet','Faye Dunaway, William Holden, Peter Finch, Robert Duvall','USA');");
            migrationBuilder.Sql("INSERT INTO movie(Id,Title,Year,Genre,Director,Actors,Country) VALUES (141,'Shutter Island',2010,'Mystery, Thriller','Martin Scorsese','Leonardo DiCaprio, Mark Ruffalo, Ben Kingsley, Max von Sydow','USA');");
            migrationBuilder.Sql("INSERT INTO movie(Id,Title,Year,Genre,Director,Actors,Country) VALUES (142,'In the Name of the Father',1993,'Biography, Drama','Jim Sheridan','Alison Crosbie, Daniel Day-Lewis, Philip King, Emma Thompson','Ireland, UK, USA');");
            migrationBuilder.Sql("INSERT INTO movie(Id,Title,Year,Genre,Director,Actors,Country) VALUES (143,'Rush',2013,'Action, Biography, Drama','Ron Howard','Chris Hemsworth, Daniel Brühl, Olivia Wilde, Alexandra Maria Lara','UK, Germany, USA');");
            migrationBuilder.Sql("INSERT INTO movie(Id,Title,Year,Genre,Director,Actors,Country) VALUES (144,'Hotel Rwanda',2004,'Biography, Drama, History','Terry George','Don Cheadle, Xolani Mali, Desmond Dube, Hakeem Kae-Kazim','UK, South Africa, Italy');");
            migrationBuilder.Sql("INSERT INTO movie(Id,Title,Year,Genre,Director,Actors,Country) VALUES (145,'Platoon',1986,'Drama, War','Oliver Stone','Tom Berenger, Keith David, Willem Dafoe, Forest Whitaker','UK, USA');");
            migrationBuilder.Sql("INSERT INTO movie(Id,Title,Year,Genre,Director,Actors,Country) VALUES (146,'Song of the Sea',2014,'Animation, Adventure, Family','Tomm Moore','David Rawle, Brendan Gleeson, Lisa Hannigan, Fionnula Flanagan','Ireland, Denmark, Belgium, Luxembourg, France');");
            migrationBuilder.Sql("INSERT INTO movie(Id,Title,Year,Genre,Director,Actors,Country) VALUES (147,'Ben-Hur',1959,'Adventure, Drama, History','William Wyler','Charlton Heston, Jack Hawkins, Haya Harareet, Stephen Boyd','USA');");
            migrationBuilder.Sql("INSERT INTO movie(Id,Title,Year,Genre,Director,Actors,Country) VALUES (148,'Stand by Me',1986,'Adventure, Drama','Rob Reiner','Wil Wheaton, River Phoenix, Corey Feldman, Jerry O''Connell','USA');");
            migrationBuilder.Sql("INSERT INTO movie(Id,Title,Year,Genre,Director,Actors,Country) VALUES (149,'Hachi: A Dog''s Tale',2009,'Drama, Family','Lasse Hallström','Richard Gere, Joan Allen, Cary-Hiroyuki Tagawa, Sarah Roemer','UK, USA');");
            migrationBuilder.Sql("INSERT INTO movie(Id,Title,Year,Genre,Director,Actors,Country) VALUES (150,'Kind Hearts and Coronets',1949,'Comedy, Crime','Robert Hamer','Dennis Price, Valerie Hobson, Joan Greenwood, Alec Guinness','UK');");
            migrationBuilder.Sql("INSERT INTO movie(Id,Title,Year,Genre,Director,Actors,Country) VALUES (151,'The Maltese Falcon',1941,'Film-Noir, Mystery','John Huston','Humphrey Bogart, Mary Astor, Gladys George, Peter Lorre','USA');");
            migrationBuilder.Sql("INSERT INTO movie(Id,Title,Year,Genre,Director,Actors,Country) VALUES (152,'Butch Cassidy and the Sundance Kid',1969,'Biography, Crime, Drama','George Roy Hill','Paul Newman, Robert Redford, Katharine Ross, Strother Martin','USA');");
            migrationBuilder.Sql("INSERT INTO movie(Id,Title,Year,Genre,Director,Actors,Country) VALUES (153,'The Legend of 1900',1998,'Drama, Music, Romance','Giuseppe Tornatore','Tim Roth, Pruitt Taylor Vince, Bill Nunn, Clarence Williams III','Italy');");
            migrationBuilder.Sql("INSERT INTO movie(Id,Title,Year,Genre,Director,Actors,Country) VALUES (154,'Spotlight',2015,'Crime, Drama, History','Tom McCarthy','Mark Ruffalo, Michael Keaton, Rachel McAdams, Liev Schreiber','USA, Canada');");
            migrationBuilder.Sql("INSERT INTO movie(Id,Title,Year,Genre,Director,Actors,Country) VALUES (155,'Brief Encounter',1945,'Drama, Romance','David Lean','Celia Johnson, Trevor Howard, Stanley Holloway, Joyce Carey','UK');");
            migrationBuilder.Sql("INSERT INTO movie(Id,Title,Year,Genre,Director,Actors,Country) VALUES (156,'The Best Years of Our Lives',1946,'Drama, Romance, War','William Wyler','Myrna Loy, Fredric March, Dana Andrews, Teresa Wright','USA');");
            migrationBuilder.Sql("INSERT INTO movie(Id,Title,Year,Genre,Director,Actors,Country) VALUES (157,'The Grapes of Wrath',1940,'Drama, History','John Ford','Henry Fonda, Jane Darwell, John Carradine, Charley Grapewin','USA');");
            migrationBuilder.Sql("INSERT INTO movie(Id,Title,Year,Genre,Director,Actors,Country) VALUES (158,'12 Years a Slave',2013,'Biography, Drama, History','Steve McQueen','Chiwetel Ejiofor, Dwight Henry, Dickie Gravois, Bryan Batt','USA, UK');");
            migrationBuilder.Sql("INSERT INTO movie(Id,Title,Year,Genre,Director,Actors,Country) VALUES (159,'The Grand Budapest Hotel',2014,'Adventure, Comedy, Drama','Wes Anderson','Ralph Fiennes, F. Murray Abraham, Mathieu Amalric, Adrien Brody','USA, Germany');");
            migrationBuilder.Sql("INSERT INTO movie(Id,Title,Year,Genre,Director,Actors,Country) VALUES (160,'Mad Max: Fury Road',2015,'Action, Adventure, Sci-Fi','George Miller','Tom Hardy, Charlize Theron, Nicholas Hoult, Hugh Keays-Byrne','Australia, USA');");
            migrationBuilder.Sql("INSERT INTO movie(Id,Title,Year,Genre,Director,Actors,Country) VALUES (161,'The Princess Bride',1987,'Adventure, Family, Fantasy','Rob Reiner','Cary Elwes, Mandy Patinkin, Chris Sarandon, Christopher Guest','USA');");
            migrationBuilder.Sql("INSERT INTO movie(Id,Title,Year,Genre,Director,Actors,Country) VALUES (162,'What Ever Happened to Baby Jane?',1962,'Drama, Horror, Thriller','Robert Aldrich','Bette Davis, Joan Crawford, Victor Buono, Wesley Addy','USA');");
            migrationBuilder.Sql("INSERT INTO movie(Id,Title,Year,Genre,Director,Actors,Country) VALUES (163,'Million Dollar Baby',2004,'Drama, Sport','Clint Eastwood','Clint Eastwood, Hilary Swank, Morgan Freeman, Jay Baruchel','USA');");
            migrationBuilder.Sql("INSERT INTO movie(Id,Title,Year,Genre,Director,Actors,Country) VALUES (164,'Jurassic Park',1993,'Adventure, Sci-Fi, Thriller','Steven Spielberg','Sam Neill, Laura Dern, Jeff Goldblum, Richard Attenborough','USA');");
            migrationBuilder.Sql("INSERT INTO movie(Id,Title,Year,Genre,Director,Actors,Country) VALUES (165,'Touch of Evil',1958,'Crime, Drama, Film-Noir','Orson Welles','Charlton Heston, Janet Leigh, Orson Welles, Joseph Calleia','USA');");
            migrationBuilder.Sql("INSERT INTO movie(Id,Title,Year,Genre,Director,Actors,Country) VALUES (166,'Spider-Man: Homecoming',2017,'Action, Adventure, Sci-Fi','Jon Watts','Tom Holland, Michael Keaton, Robert Downey Jr., Marisa Tomei','USA');");
            migrationBuilder.Sql("INSERT INTO movie(Id,Title,Year,Genre,Director,Actors,Country) VALUES (167,'Before Sunrise',1995,'Drama, Romance','Richard Linklater','Ethan Hawke, Julie Delpy, Andrea Eckert, Hanno Pöschl','USA, Austria, Switzerland');");
            migrationBuilder.Sql("INSERT INTO movie(Id,Title,Year,Genre,Director,Actors,Country) VALUES (168,'The Truman Show',1998,'Comedy, Drama, Sci-Fi','Peter Weir','Jim Carrey, Laura Linney, Noah Emmerich, Natascha McElhone','USA');");
            migrationBuilder.Sql("INSERT INTO movie(Id,Title,Year,Genre,Director,Actors,Country) VALUES (169,'Harry Potter and the Deathly Hallows: Part 2',2011,'Adventure, Drama, Fantasy','David Yates','Ralph Fiennes, Michael Gambon, Alan Rickman, Daniel Radcliffe','USA, UK');");
            migrationBuilder.Sql("INSERT INTO movie(Id,Title,Year,Genre,Director,Actors,Country) VALUES (170,'Star Wars: The Force Awakens',2015,'Action, Adventure, Fantasy','J.J. Abrams','Harrison Ford, Mark Hamill, Carrie Fisher, Adam Driver','USA');");
            migrationBuilder.Sql("INSERT INTO movie(Id,Title,Year,Genre,Director,Actors,Country) VALUES (171,'Paris, Texas',1984,'Drama','Wim Wenders','Harry Dean Stanton, Sam Berry, Bernhard Wicki, Dean Stockwell','UK, France, West Germany');");
            migrationBuilder.Sql("INSERT INTO movie(Id,Title,Year,Genre,Director,Actors,Country) VALUES (172,'The Last Picture Show',1971,'Drama','Peter Bogdanovich','Timothy Bottoms, Jeff Bridges, Cybill Shepherd, Ben Johnson','USA');");
            migrationBuilder.Sql("INSERT INTO movie(Id,Title,Year,Genre,Director,Actors,Country) VALUES (173,'Gandhi',1982,'Biography, Drama, History','Richard Attenborough','Ben Kingsley, Candice Bergen, Edward Fox, John Gielgud','UK, India, USA');");
            migrationBuilder.Sql("INSERT INTO movie(Id,Title,Year,Genre,Director,Actors,Country) VALUES (174,'Barry Lyndon',1975,'Adventure, Drama, History','Stanley Kubrick','Ryan O''Neal, Marisa Berenson, Patrick Magee, Hardy Krüger','UK, USA, Ireland');");
            migrationBuilder.Sql("INSERT INTO movie(Id,Title,Year,Genre,Director,Actors,Country) VALUES (175,'Rocky',1976,'Drama, Sport','John G. Avildsen','Sylvester Stallone, Talia Shire, Burt Young, Carl Weathers','USA');");
            migrationBuilder.Sql("INSERT INTO movie(Id,Title,Year,Genre,Director,Actors,Country) VALUES (176,'Annie Hall',1977,'Comedy, Romance','Woody Allen','Woody Allen, Diane Keaton, Tony Roberts, Carol Kane','USA');");
            migrationBuilder.Sql("INSERT INTO movie(Id,Title,Year,Genre,Director,Actors,Country) VALUES (177,'Prisoners',2013,'Crime, Drama, Mystery','Denis Villeneuve','Hugh Jackman, Jake Gyllenhaal, Viola Davis, Maria Bello','USA');");
            migrationBuilder.Sql("INSERT INTO movie(Id,Title,Year,Genre,Director,Actors,Country) VALUES (178,'Donnie Darko',2001,'Drama, Sci-Fi, Thriller','Richard Kelly','Jake Gyllenhaal, Holmes Osborne, Maggie Gyllenhaal, Daveigh Chase','USA');");
            migrationBuilder.Sql("INSERT INTO movie(Id,Title,Year,Genre,Director,Actors,Country) VALUES (179,'Catch Me If You Can',2002,'Biography, Crime, Drama','Steven Spielberg','Leonardo DiCaprio, Tom Hanks, Christopher Walken, Martin Sheen','USA, Canada');");
            migrationBuilder.Sql("INSERT INTO movie(Id,Title,Year,Genre,Director,Actors,Country) VALUES (180,'The Man Who Shot Liberty Valance',1962,'Action, Drama, Western','John Ford','John Wayne, James Stewart, Vera Miles, Lee Marvin','USA');");
            migrationBuilder.Sql("INSERT INTO movie(Id,Title,Year,Genre,Director,Actors,Country) VALUES (181,'Laura',1944,'Drama, Film-Noir, Mystery','Otto Preminger','Gene Tierney, Dana Andrews, Clifton Webb, Vincent Price','USA');");
            migrationBuilder.Sql("INSERT INTO movie(Id,Title,Year,Genre,Director,Actors,Country) VALUES (182,'Monsters, Inc.',2001,'Animation, Adventure, Comedy','Pete Docter, David Silverman, Lee Unkrich','John Goodman, Billy Crystal, Mary Gibbs, Steve Buscemi','USA');");
            migrationBuilder.Sql("INSERT INTO movie(Id,Title,Year,Genre,Director,Actors,Country) VALUES (183,'The Bourne Ultimatum',2007,'Action, Mystery, Thriller','Paul Greengrass','Matt Damon, Julia Stiles, David Strathairn, Scott Glenn','USA, Germany');");
            migrationBuilder.Sql("INSERT INTO movie(Id,Title,Year,Genre,Director,Actors,Country) VALUES (184,'Cat on a Hot Tin Roof',1958,'Drama, Romance','Richard Brooks','Elizabeth Taylor, Paul Newman, Burl Ives, Jack Carson','USA');");
            migrationBuilder.Sql("INSERT INTO movie(Id,Title,Year,Genre,Director,Actors,Country) VALUES (185,'The Wizard of Oz',1939,'Adventure, Family, Fantasy','Victor Fleming, George Cukor, Mervyn LeRoy, Norman Taurog, King Vidor','Judy Garland, Frank Morgan, Ray Bolger, Bert Lahr','USA');");
            migrationBuilder.Sql("INSERT INTO movie(Id,Title,Year,Genre,Director,Actors,Country) VALUES (186,'Sleuth',1972,'Mystery, Thriller','Joseph L. Mankiewicz','Laurence Olivier, Michael Caine, Alec Cawthorne, John Matthews','UK, USA');");
            migrationBuilder.Sql("INSERT INTO movie(Id,Title,Year,Genre,Director,Actors,Country) VALUES (187,'Roman Holiday',1953,'Comedy, Romance','William Wyler','Gregory Peck, Audrey Hepburn, Eddie Albert, Hartley Power','USA');");
            migrationBuilder.Sql("INSERT INTO movie(Id,Title,Year,Genre,Director,Actors,Country) VALUES (188,'Out of the Past',1947,'Crime, Drama, Film-Noir','Jacques Tourneur','Robert Mitchum, Jane Greer, Kirk Douglas, Rhonda Fleming','USA');");
            migrationBuilder.Sql("INSERT INTO movie(Id,Title,Year,Genre,Director,Actors,Country) VALUES (189,'Anatomy of a Murder',1959,'Crime, Drama, Mystery','Otto Preminger','James Stewart, Lee Remick, Ben Gazzara, Arthur O''Connell','USA');");
            migrationBuilder.Sql("INSERT INTO movie(Id,Title,Year,Genre,Director,Actors,Country) VALUES (190,'Who''s Afraid of Virginia Woolf?',1966,'Drama','Mike Nichols','Elizabeth Taylor, Richard Burton, George Segal, Sandy Dennis','USA');");
            migrationBuilder.Sql("INSERT INTO movie(Id,Title,Year,Genre,Director,Actors,Country) VALUES (191,'The Terminator',1984,'Action, Sci-Fi','James Cameron','Arnold Schwarzenegger, Michael Biehn, Linda Hamilton, Paul Winfield','UK, USA');");
            migrationBuilder.Sql("INSERT INTO movie(Id,Title,Year,Genre,Director,Actors,Country) VALUES (192,'Groundhog Day',1993,'Comedy, Fantasy, Romance','Harold Ramis','Bill Murray, Andie MacDowell, Chris Elliott, Stephen Tobolowsky','USA');");
            migrationBuilder.Sql("INSERT INTO movie(Id,Title,Year,Genre,Director,Actors,Country) VALUES (193,'The Help',2011,'Drama','Tate Taylor','Emma Stone, Viola Davis, Bryce Dallas Howard, Octavia Spencer','USA, India, United Arab Emirates');");
            migrationBuilder.Sql("INSERT INTO movie(Id,Title,Year,Genre,Director,Actors,Country) VALUES (194,'Strangers on a Train',1951,'Crime, Film-Noir, Thriller','Alfred Hitchcock','Farley Granger, Ruth Roman, Robert Walker, Leo G. Carroll','USA');");
            migrationBuilder.Sql("INSERT INTO movie(Id,Title,Year,Genre,Director,Actors,Country) VALUES (195,'The Night of the Hunter',1955,'Crime, Drama, Film-Noir','Charles Laughton','Robert Mitchum, Shelley Winters, Lillian Gish, James Gleason','USA');");
            migrationBuilder.Sql("INSERT INTO movie(Id,Title,Year,Genre,Director,Actors,Country) VALUES (196,'All Quiet on the Western Front',1930,'Drama, War','Lewis Milestone','Louis Wolheim, Lew Ayres, John Wray, Arnold Lucy','USA');");
            migrationBuilder.Sql("INSERT INTO movie(Id,Title,Year,Genre,Director,Actors,Country) VALUES (197,'Beauty and the Beast',1991,'Animation, Family, Fantasy','Gary Trousdale, Kirk Wise','Robby Benson, Jesse Corti, Rex Everhart, Angela Lansbury','USA');");
            migrationBuilder.Sql("INSERT INTO movie(Id,Title,Year,Genre,Director,Actors,Country) VALUES (198,'Lion',2016,'Biography, Drama','Garth Davis','Sunny Pawar, Abhishek Bharate, Priyanka Bose, Khushi Solanki','UK, Australia, USA');");
            migrationBuilder.Sql("INSERT INTO movie(Id,Title,Year,Genre,Director,Actors,Country) VALUES (199,'Twelve Monkeys',1995,'Mystery, Sci-Fi, Thriller','Terry Gilliam','Joseph Melito, Bruce Willis, Jon Seda, Michael Chance','USA');");
            migrationBuilder.Sql("INSERT INTO movie(Id,Title,Year,Genre,Director,Actors,Country) VALUES (200,'Guardians of the Galaxy',2014,'Action, Adventure, Sci-Fi','James Gunn','Chris Pratt, Zoe Saldana, Dave Bautista, Vin Diesel','USA, UK');");
            migrationBuilder.Sql("INSERT INTO movie(Id,Title,Year,Genre,Director,Actors,Country) VALUES (201,'Dog Day Afternoon',1975,'Biography, Crime, Drama','Sidney Lumet','Penelope Allen, Sully Boyar, John Cazale, Beulah Garrick','USA');");
            migrationBuilder.Sql("INSERT INTO movie(Id,Title,Year,Genre,Director,Actors,Country) VALUES (202,'Jaws',1975,'Adventure, Drama, Thriller','Steven Spielberg','Roy Scheider, Robert Shaw, Richard Dreyfuss, Lorraine Gary','USA');");
            migrationBuilder.Sql("INSERT INTO movie(Id,Title,Year,Genre,Director,Actors,Country) VALUES (203,'Zootopia',2016,'Animation, Adventure, Comedy','Jared Bush, Byron Howard, Rich Moore','Ginnifer Goodwin, Jason Bateman, Idris Elba, Jenny Slate','USA');");
            migrationBuilder.Sql("INSERT INTO movie(Id,Title,Year,Genre,Director,Actors,Country) VALUES (204,'Guardians of the Galaxy Vol. 2',2017,'Action, Adventure, Sci-Fi','James Gunn','Chris Pratt, Zoe Saldana, Dave Bautista, Vin Diesel','USA');");
            migrationBuilder.Sql("INSERT INTO movie(Id,Title,Year,Genre,Director,Actors,Country) VALUES (205,'Pirates of the Caribbean: The Curse of the Black Pearl',2003,'Action, Adventure, Fantasy','Gore Verbinski','Johnny Depp, Geoffrey Rush, Orlando Bloom, Keira Knightley','USA');");
            migrationBuilder.Sql("INSERT INTO movie(Id,Title,Year,Genre,Director,Actors,Country) VALUES (206,'Before Sunset',2004,'Drama, Romance','Richard Linklater','Ethan Hawke, Julie Delpy, Vernon Dobtcheff, Louise Lemoine Torrès','USA');");
            migrationBuilder.Sql("INSERT INTO movie(Id,Title,Year,Genre,Director,Actors,Country) VALUES (207,'The Imitation Game',2014,'Biography, Drama, Thriller','Morten Tyldum','Benedict Cumberbatch, Keira Knightley, Matthew Goode, Rory Kinnear','UK, USA');");
            migrationBuilder.Sql("INSERT INTO movie(Id,Title,Year,Genre,Director,Actors,Country) VALUES (208,'Young Frankenstein',1974,'Comedy','Mel Brooks','Gene Wilder, Peter Boyle, Marty Feldman, Madeline Kahn','USA');");
            migrationBuilder.Sql("INSERT INTO movie(Id,Title,Year,Genre,Director,Actors,Country) VALUES (209,'Stalag 17',1953,'Drama, War','Billy Wilder','William Holden, Don Taylor, Otto Preminger, Robert Strauss','USA');");
            migrationBuilder.Sql("INSERT INTO movie(Id,Title,Year,Genre,Director,Actors,Country) VALUES (210,'Dogville',2003,'Crime, Drama','Lars von Trier','Nicole Kidman, Harriet Andersson, Lauren Bacall, Jean-Marc Barr','Netherlands, Denmark, UK, France, Finland, Sweden, Germany, Italy, Norway');");
            migrationBuilder.Sql("INSERT INTO movie(Id,Title,Year,Genre,Director,Actors,Country) VALUES (211,'Dead Poets Society',1989,'Comedy, Drama','Peter Weir','Robin Williams, Robert Sean Leonard, Ethan Hawke, Josh Charles','USA');");
            migrationBuilder.Sql("INSERT INTO movie(Id,Title,Year,Genre,Director,Actors,Country) VALUES (212,'High Noon',1952,'Drama, Thriller, Western','Fred Zinnemann','Gary Cooper, Thomas Mitchell, Lloyd Bridges, Katy Jurado','USA');");
            migrationBuilder.Sql("INSERT INTO movie(Id,Title,Year,Genre,Director,Actors,Country) VALUES (213,'Papillon',1973,'Biography, Crime, Drama','Franklin J. Schaffner','Steve McQueen, Dustin Hoffman, Victor Jory, Don Gordon','France, USA');");
            migrationBuilder.Sql("INSERT INTO movie(Id,Title,Year,Genre,Director,Actors,Country) VALUES (214,'A Streetcar Named Desire',1951,'Drama','Elia Kazan','Vivien Leigh, Marlon Brando, Kim Hunter, Karl Malden','USA');");
            migrationBuilder.Sql("INSERT INTO movie(Id,Title,Year,Genre,Director,Actors,Country) VALUES (215,'Arsenic and Old Lace',1944,'Comedy, Crime, Thriller','Frank Capra','Cary Grant, Priscilla Lane, Raymond Massey, Jack Carson','USA');");
            migrationBuilder.Sql("INSERT INTO movie(Id,Title,Year,Genre,Director,Actors,Country) VALUES (216,'Sin City',2005,'Crime, Thriller','Frank Miller, Robert Rodriguez, Quentin Tarantino','Jessica Alba, Devon Aoki, Alexis Bledel, Powers Boothe','USA');");
            migrationBuilder.Sql("INSERT INTO movie(Id,Title,Year,Genre,Director,Actors,Country) VALUES (217,'The Hustler',1961,'Drama, Sport','Robert Rossen','Paul Newman, Jackie Gleason, Piper Laurie, George C. Scott','USA');");
            migrationBuilder.Sql("INSERT INTO movie(Id,Title,Year,Genre,Director,Actors,Country) VALUES (218,'A Night at the Opera',1935,'Comedy, Music, Musical','Sam Wood, Edmund Goulding','Groucho Marx, Chico Marx, Harpo Marx, Kitty Carlisle','USA');");
            migrationBuilder.Sql("INSERT INTO movie(Id,Title,Year,Genre,Director,Actors,Country) VALUES (219,'The Killing',1956,'Crime, Drama, Film-Noir','Stanley Kubrick','Sterling Hayden, Coleen Gray, Vince Edwards, Jay C. Flippen','USA');");
            migrationBuilder.Sql("INSERT INTO movie(Id,Title,Year,Genre,Director,Actors,Country) VALUES (220,'The Avengers',2012,'Action, Sci-Fi','Joss Whedon','Robert Downey Jr., Chris Evans, Mark Ruffalo, Chris Hemsworth','USA');");
            migrationBuilder.Sql("INSERT INTO movie(Id,Title,Year,Genre,Director,Actors,Country) VALUES (221,'Notorious',1946,'Drama, Film-Noir, Romance','Alfred Hitchcock','Cary Grant, Ingrid Bergman, Claude Rains, Louis Calhern','USA');");
            migrationBuilder.Sql("INSERT INTO movie(Id,Title,Year,Genre,Director,Actors,Country) VALUES (222,'Harvey',1950,'Comedy, Drama, Fantasy','Henry Koster','Wallace Ford, William H. Lynn, Victoria Horne, Jesse White','USA');");
            migrationBuilder.Sql("INSERT INTO movie(Id,Title,Year,Genre,Director,Actors,Country) VALUES (223,'The Martian',2015,'Adventure, Drama, Sci-Fi','Ridley Scott','Matt Damon, Jessica Chastain, Kristen Wiig, Jeff Daniels','USA, UK');");
            migrationBuilder.Sql("INSERT INTO movie(Id,Title,Year,Genre,Director,Actors,Country) VALUES (224,'The Exorcist',1973,'Horror','William Friedkin','Ellen Burstyn, Max von Sydow, Lee J. Cobb, Kitty Winn','USA');");
            migrationBuilder.Sql("INSERT INTO movie(Id,Title,Year,Genre,Director,Actors,Country) VALUES (225,'Rio Bravo',1959,'Action, Drama, Western','Howard Hawks','John Wayne, Dean Martin, Ricky Nelson, Angie Dickinson','USA');");
            migrationBuilder.Sql("INSERT INTO movie(Id,Title,Year,Genre,Director,Actors,Country) VALUES (226,'The Philadelphia Story',1940,'Comedy, Romance','George Cukor','Cary Grant, Katharine Hepburn, James Stewart, Ruth Hussey','USA');");
            migrationBuilder.Sql("INSERT INTO movie(Id,Title,Year,Genre,Director,Actors,Country) VALUES (227,'Rope',1948,'Crime, Drama, Thriller','Alfred Hitchcock','John Dall, Farley Granger, Edith Evanson, Douglas Dick','USA');");
            migrationBuilder.Sql("INSERT INTO movie(Id,Title,Year,Genre,Director,Actors,Country) VALUES (228,'The Big Sleep',1946,'Crime, Film-Noir, Mystery','Howard Hawks','Humphrey Bogart, Lauren Bacall, John Ridgely, Martha Vickers','USA');");
            migrationBuilder.Sql("INSERT INTO movie(Id,Title,Year,Genre,Director,Actors,Country) VALUES (229,'Pink Floyd: The Wall',1982,'Animation, Drama, Fantasy','Alan Parker','Bob Geldof, Christine Hargreaves, James Laurenson, Eleanor David','UK');");
            migrationBuilder.Sql("INSERT INTO movie(Id,Title,Year,Genre,Director,Actors,Country) VALUES (230,'The King''s Speech',2010,'Biography, Drama','Tom Hooper','Colin Firth, Helena Bonham Carter, Derek Jacobi, Robert Portal','UK, USA, Australia');");
            migrationBuilder.Sql("INSERT INTO movie(Id,Title,Year,Genre,Director,Actors,Country) VALUES (231,'A Christmas Story',1983,'Comedy, Family','Bob Clark','Melinda Dillon, Darren McGavin, Peter Billingsley, Scott Schwartz','USA, Canada');");
            migrationBuilder.Sql("INSERT INTO movie(Id,Title,Year,Genre,Director,Actors,Country) VALUES (232,'The Graduate',1967,'Comedy, Drama','Mike Nichols','Anne Bancroft, Dustin Hoffman, Katharine Ross, William Daniels','USA');");
            migrationBuilder.Sql("INSERT INTO movie(Id,Title,Year,Genre,Director,Actors,Country) VALUES (233,'JFK',1991,'Drama, History, Thriller','Oliver Stone','Sally Kirkland, Anthony Ramirez, Ray LePere, Steve Reed','France, USA');");
            migrationBuilder.Sql("INSERT INTO movie(Id,Title,Year,Genre,Director,Actors,Country) VALUES (234,'Sling Blade',1996,'Drama','Billy Bob Thornton','Billy Bob Thornton, Dwight Yoakam, J.T. Walsh, John Ritter','USA');");
            migrationBuilder.Sql("INSERT INTO movie(Id,Title,Year,Genre,Director,Actors,Country) VALUES (235,'Blood Diamond',2006,'Adventure, Drama, Thriller','Edward Zwick','Leonardo DiCaprio, Djimon Hounsou, Jennifer Connelly, Kagiso Kuypers','Germany, USA');");
            migrationBuilder.Sql("INSERT INTO movie(Id,Title,Year,Genre,Director,Actors,Country) VALUES (236,'Magnolia',1999,'Drama','Paul Thomas Anderson','Pat Healy, Genevieve Zweig, Mark Flanagan, Neil Flynn','USA');");
            migrationBuilder.Sql("INSERT INTO movie(Id,Title,Year,Genre,Director,Actors,Country) VALUES (237,'Rain Man',1988,'Drama','Barry Levinson','Dustin Hoffman, Tom Cruise, Valeria Golino, Gerald R. Molen','USA');");
            migrationBuilder.Sql("INSERT INTO movie(Id,Title,Year,Genre,Director,Actors,Country) VALUES (238,'The Revenant',2015,'Adventure, Drama, Thriller','Alejandro González Iñárritu','Leonardo DiCaprio, Tom Hardy, Domhnall Gleeson, Will Poulter','Hong Kong, Taiwan, USA');");
            migrationBuilder.Sql("INSERT INTO movie(Id,Title,Year,Genre,Director,Actors,Country) VALUES (239,'The Nightmare Before Christmas',1993,'Animation, Family, Fantasy','Henry Selick','Danny Elfman, Chris Sarandon, Catherine O''Hara, William Hickey','USA');");
            migrationBuilder.Sql("INSERT INTO movie(Id,Title,Year,Genre,Director,Actors,Country) VALUES (240,'The Manchurian Candidate',1962,'Drama, Thriller','John Frankenheimer','Frank Sinatra, Laurence Harvey, Janet Leigh, Angela Lansbury','USA');");
            migrationBuilder.Sql("INSERT INTO movie(Id,Title,Year,Genre,Director,Actors,Country) VALUES (241,'Deadpool',2016,'Action, Adventure, Comedy','Tim Miller','Ryan Reynolds, Karan Soni, Ed Skrein, Michael Benyaer','USA');");
            migrationBuilder.Sql("INSERT INTO movie(Id,Title,Year,Genre,Director,Actors,Country) VALUES (242,'The Wild Bunch',1969,'Action, Adventure, Western','Sam Peckinpah','William Holden, Ernest Borgnine, Robert Ryan, Edmond O''Brien','USA');");
            migrationBuilder.Sql("INSERT INTO movie(Id,Title,Year,Genre,Director,Actors,Country) VALUES (243,'Aladdin',1992,'Animation, Adventure, Comedy','Ron Clements, John Musker','Scott Weinger, Robin Williams, Linda Larkin, Jonathan Freeman','USA');");
            migrationBuilder.Sql("INSERT INTO movie(Id,Title,Year,Genre,Director,Actors,Country) VALUES (244,'Big Fish',2003,'Adventure, Drama, Fantasy','Tim Burton','Ewan McGregor, Albert Finney, Billy Crudup, Jessica Lange','USA');");
            migrationBuilder.Sql("INSERT INTO movie(Id,Title,Year,Genre,Director,Actors,Country) VALUES (245,'Patton',1970,'Biography, Drama, War','Franklin J. Schaffner','George C. Scott, Karl Malden, Stephen Young, Michael Strong','USA');");
            migrationBuilder.Sql("INSERT INTO movie(Id,Title,Year,Genre,Director,Actors,Country) VALUES (246,'The Lost Weekend',1945,'Drama, Film-Noir','Billy Wilder','Ray Milland, Jane Wyman, Phillip Terry, Howard Da Silva','USA');");
            migrationBuilder.Sql("INSERT INTO movie(Id,Title,Year,Genre,Director,Actors,Country) VALUES (247,'Short Term 12',2013,'Drama','Destin Daniel Cretton','Brie Larson, John Gallagher Jr., Stephanie Beatriz, Rami Malek','USA');");
            migrationBuilder.Sql("INSERT INTO movie(Id,Title,Year,Genre,Director,Actors,Country) VALUES (248,'His Girl Friday',1940,'Comedy, Drama, Romance','Howard Hawks','Cary Grant, Rosalind Russell, Ralph Bellamy, Gene Lockhart','USA');");
            migrationBuilder.Sql("INSERT INTO movie(Id,Title,Year,Genre,Director,Actors,Country) VALUES (249,'The Straight Story',1999,'Biography, Drama','David Lynch','Sissy Spacek, Jane Galloway Heitz, Joseph A. Carpenter, Donald Wiegert','France, UK, USA');");
            migrationBuilder.Sql("INSERT INTO movie(Id,Title,Year,Genre,Director,Actors,Country) VALUES (250,'Slumdog Millionaire',2008,'Drama','Danny Boyle, Loveleen Tandan','Dev Patel, Saurabh Shukla, Anil Kapoor, Raj Zutshi','UK, France, USA');");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("DELETE FROM movie WHERE Id = 250");
            migrationBuilder.Sql("DELETE FROM movie WHERE Id = 249");
            migrationBuilder.Sql("DELETE FROM movie WHERE Id = 248");
            migrationBuilder.Sql("DELETE FROM movie WHERE Id = 247");
            migrationBuilder.Sql("DELETE FROM movie WHERE Id = 246");
            migrationBuilder.Sql("DELETE FROM movie WHERE Id = 245");
            migrationBuilder.Sql("DELETE FROM movie WHERE Id = 244");
            migrationBuilder.Sql("DELETE FROM movie WHERE Id = 243");
            migrationBuilder.Sql("DELETE FROM movie WHERE Id = 242");
            migrationBuilder.Sql("DELETE FROM movie WHERE Id = 241");
            migrationBuilder.Sql("DELETE FROM movie WHERE Id = 240");
            migrationBuilder.Sql("DELETE FROM movie WHERE Id = 239");
            migrationBuilder.Sql("DELETE FROM movie WHERE Id = 238");
            migrationBuilder.Sql("DELETE FROM movie WHERE Id = 237");
            migrationBuilder.Sql("DELETE FROM movie WHERE Id = 236");
            migrationBuilder.Sql("DELETE FROM movie WHERE Id = 235");
            migrationBuilder.Sql("DELETE FROM movie WHERE Id = 234");
            migrationBuilder.Sql("DELETE FROM movie WHERE Id = 233");
            migrationBuilder.Sql("DELETE FROM movie WHERE Id = 232");
            migrationBuilder.Sql("DELETE FROM movie WHERE Id = 231");
            migrationBuilder.Sql("DELETE FROM movie WHERE Id = 230");
            migrationBuilder.Sql("DELETE FROM movie WHERE Id = 229");
            migrationBuilder.Sql("DELETE FROM movie WHERE Id = 228");
            migrationBuilder.Sql("DELETE FROM movie WHERE Id = 227");
            migrationBuilder.Sql("DELETE FROM movie WHERE Id = 226");
            migrationBuilder.Sql("DELETE FROM movie WHERE Id = 225");
            migrationBuilder.Sql("DELETE FROM movie WHERE Id = 224");
            migrationBuilder.Sql("DELETE FROM movie WHERE Id = 223");
            migrationBuilder.Sql("DELETE FROM movie WHERE Id = 222");
            migrationBuilder.Sql("DELETE FROM movie WHERE Id = 221");
            migrationBuilder.Sql("DELETE FROM movie WHERE Id = 220");
            migrationBuilder.Sql("DELETE FROM movie WHERE Id = 219");
            migrationBuilder.Sql("DELETE FROM movie WHERE Id = 218");
            migrationBuilder.Sql("DELETE FROM movie WHERE Id = 217");
            migrationBuilder.Sql("DELETE FROM movie WHERE Id = 216");
            migrationBuilder.Sql("DELETE FROM movie WHERE Id = 215");
            migrationBuilder.Sql("DELETE FROM movie WHERE Id = 214");
            migrationBuilder.Sql("DELETE FROM movie WHERE Id = 213");
            migrationBuilder.Sql("DELETE FROM movie WHERE Id = 212");
            migrationBuilder.Sql("DELETE FROM movie WHERE Id = 211");
            migrationBuilder.Sql("DELETE FROM movie WHERE Id = 210");
            migrationBuilder.Sql("DELETE FROM movie WHERE Id = 209");
            migrationBuilder.Sql("DELETE FROM movie WHERE Id = 208");
            migrationBuilder.Sql("DELETE FROM movie WHERE Id = 207");
            migrationBuilder.Sql("DELETE FROM movie WHERE Id = 206");
            migrationBuilder.Sql("DELETE FROM movie WHERE Id = 205");
            migrationBuilder.Sql("DELETE FROM movie WHERE Id = 204");
            migrationBuilder.Sql("DELETE FROM movie WHERE Id = 203");
            migrationBuilder.Sql("DELETE FROM movie WHERE Id = 202");
            migrationBuilder.Sql("DELETE FROM movie WHERE Id = 201");
            migrationBuilder.Sql("DELETE FROM movie WHERE Id = 200");
            migrationBuilder.Sql("DELETE FROM movie WHERE Id = 199");
            migrationBuilder.Sql("DELETE FROM movie WHERE Id = 198");
            migrationBuilder.Sql("DELETE FROM movie WHERE Id = 197");
            migrationBuilder.Sql("DELETE FROM movie WHERE Id = 196");
            migrationBuilder.Sql("DELETE FROM movie WHERE Id = 195");
            migrationBuilder.Sql("DELETE FROM movie WHERE Id = 194");
            migrationBuilder.Sql("DELETE FROM movie WHERE Id = 193");
            migrationBuilder.Sql("DELETE FROM movie WHERE Id = 192");
            migrationBuilder.Sql("DELETE FROM movie WHERE Id = 191");
            migrationBuilder.Sql("DELETE FROM movie WHERE Id = 190");
            migrationBuilder.Sql("DELETE FROM movie WHERE Id = 189");
            migrationBuilder.Sql("DELETE FROM movie WHERE Id = 188");
            migrationBuilder.Sql("DELETE FROM movie WHERE Id = 187");
            migrationBuilder.Sql("DELETE FROM movie WHERE Id = 186");
            migrationBuilder.Sql("DELETE FROM movie WHERE Id = 185");
            migrationBuilder.Sql("DELETE FROM movie WHERE Id = 184");
            migrationBuilder.Sql("DELETE FROM movie WHERE Id = 183");
            migrationBuilder.Sql("DELETE FROM movie WHERE Id = 182");
            migrationBuilder.Sql("DELETE FROM movie WHERE Id = 181");
            migrationBuilder.Sql("DELETE FROM movie WHERE Id = 180");
            migrationBuilder.Sql("DELETE FROM movie WHERE Id = 179");
            migrationBuilder.Sql("DELETE FROM movie WHERE Id = 178");
            migrationBuilder.Sql("DELETE FROM movie WHERE Id = 177");
            migrationBuilder.Sql("DELETE FROM movie WHERE Id = 176");
            migrationBuilder.Sql("DELETE FROM movie WHERE Id = 175");
            migrationBuilder.Sql("DELETE FROM movie WHERE Id = 174");
            migrationBuilder.Sql("DELETE FROM movie WHERE Id = 173");
            migrationBuilder.Sql("DELETE FROM movie WHERE Id = 172");
            migrationBuilder.Sql("DELETE FROM movie WHERE Id = 171");
            migrationBuilder.Sql("DELETE FROM movie WHERE Id = 170");
            migrationBuilder.Sql("DELETE FROM movie WHERE Id = 169");
            migrationBuilder.Sql("DELETE FROM movie WHERE Id = 168");
            migrationBuilder.Sql("DELETE FROM movie WHERE Id = 167");
            migrationBuilder.Sql("DELETE FROM movie WHERE Id = 166");
            migrationBuilder.Sql("DELETE FROM movie WHERE Id = 165");
            migrationBuilder.Sql("DELETE FROM movie WHERE Id = 164");
            migrationBuilder.Sql("DELETE FROM movie WHERE Id = 163");
            migrationBuilder.Sql("DELETE FROM movie WHERE Id = 162");
            migrationBuilder.Sql("DELETE FROM movie WHERE Id = 161");
            migrationBuilder.Sql("DELETE FROM movie WHERE Id = 160");
            migrationBuilder.Sql("DELETE FROM movie WHERE Id = 159");
            migrationBuilder.Sql("DELETE FROM movie WHERE Id = 158");
            migrationBuilder.Sql("DELETE FROM movie WHERE Id = 157");
            migrationBuilder.Sql("DELETE FROM movie WHERE Id = 156");
            migrationBuilder.Sql("DELETE FROM movie WHERE Id = 155");
            migrationBuilder.Sql("DELETE FROM movie WHERE Id = 154");
            migrationBuilder.Sql("DELETE FROM movie WHERE Id = 153");
            migrationBuilder.Sql("DELETE FROM movie WHERE Id = 152");
            migrationBuilder.Sql("DELETE FROM movie WHERE Id = 151");
            migrationBuilder.Sql("DELETE FROM movie WHERE Id = 150");
            migrationBuilder.Sql("DELETE FROM movie WHERE Id = 149");
            migrationBuilder.Sql("DELETE FROM movie WHERE Id = 148");
            migrationBuilder.Sql("DELETE FROM movie WHERE Id = 147");
            migrationBuilder.Sql("DELETE FROM movie WHERE Id = 146");
            migrationBuilder.Sql("DELETE FROM movie WHERE Id = 145");
            migrationBuilder.Sql("DELETE FROM movie WHERE Id = 144");
            migrationBuilder.Sql("DELETE FROM movie WHERE Id = 143");
            migrationBuilder.Sql("DELETE FROM movie WHERE Id = 142");
            migrationBuilder.Sql("DELETE FROM movie WHERE Id = 141");
            migrationBuilder.Sql("DELETE FROM movie WHERE Id = 140");
            migrationBuilder.Sql("DELETE FROM movie WHERE Id = 139");
            migrationBuilder.Sql("DELETE FROM movie WHERE Id = 138");
            migrationBuilder.Sql("DELETE FROM movie WHERE Id = 137");
            migrationBuilder.Sql("DELETE FROM movie WHERE Id = 136");
            migrationBuilder.Sql("DELETE FROM movie WHERE Id = 135");
            migrationBuilder.Sql("DELETE FROM movie WHERE Id = 134");
            migrationBuilder.Sql("DELETE FROM movie WHERE Id = 133");
            migrationBuilder.Sql("DELETE FROM movie WHERE Id = 132");
            migrationBuilder.Sql("DELETE FROM movie WHERE Id = 131");
            migrationBuilder.Sql("DELETE FROM movie WHERE Id = 130");
            migrationBuilder.Sql("DELETE FROM movie WHERE Id = 129");
            migrationBuilder.Sql("DELETE FROM movie WHERE Id = 128");
            migrationBuilder.Sql("DELETE FROM movie WHERE Id = 127");
            migrationBuilder.Sql("DELETE FROM movie WHERE Id = 126");
            migrationBuilder.Sql("DELETE FROM movie WHERE Id = 125");
            migrationBuilder.Sql("DELETE FROM movie WHERE Id = 124");
            migrationBuilder.Sql("DELETE FROM movie WHERE Id = 123");
            migrationBuilder.Sql("DELETE FROM movie WHERE Id = 122");
            migrationBuilder.Sql("DELETE FROM movie WHERE Id = 121");
            migrationBuilder.Sql("DELETE FROM movie WHERE Id = 120");
            migrationBuilder.Sql("DELETE FROM movie WHERE Id = 119");
            migrationBuilder.Sql("DELETE FROM movie WHERE Id = 118");
            migrationBuilder.Sql("DELETE FROM movie WHERE Id = 117");
            migrationBuilder.Sql("DELETE FROM movie WHERE Id = 116");
            migrationBuilder.Sql("DELETE FROM movie WHERE Id = 115");
            migrationBuilder.Sql("DELETE FROM movie WHERE Id = 114");
            migrationBuilder.Sql("DELETE FROM movie WHERE Id = 113");
            migrationBuilder.Sql("DELETE FROM movie WHERE Id = 112");
            migrationBuilder.Sql("DELETE FROM movie WHERE Id = 111");
            migrationBuilder.Sql("DELETE FROM movie WHERE Id = 110");
            migrationBuilder.Sql("DELETE FROM movie WHERE Id = 109");
            migrationBuilder.Sql("DELETE FROM movie WHERE Id = 108");
            migrationBuilder.Sql("DELETE FROM movie WHERE Id = 107");
            migrationBuilder.Sql("DELETE FROM movie WHERE Id = 106");
            migrationBuilder.Sql("DELETE FROM movie WHERE Id = 105");
            migrationBuilder.Sql("DELETE FROM movie WHERE Id = 104");
            migrationBuilder.Sql("DELETE FROM movie WHERE Id = 103");
            migrationBuilder.Sql("DELETE FROM movie WHERE Id = 102");
            migrationBuilder.Sql("DELETE FROM movie WHERE Id = 101");
            migrationBuilder.Sql("DELETE FROM movie WHERE Id = 100");
            migrationBuilder.Sql("DELETE FROM movie WHERE Id = 99");
            migrationBuilder.Sql("DELETE FROM movie WHERE Id = 98");
            migrationBuilder.Sql("DELETE FROM movie WHERE Id = 97");
            migrationBuilder.Sql("DELETE FROM movie WHERE Id = 96");
            migrationBuilder.Sql("DELETE FROM movie WHERE Id = 95");
            migrationBuilder.Sql("DELETE FROM movie WHERE Id = 94");
            migrationBuilder.Sql("DELETE FROM movie WHERE Id = 93");
            migrationBuilder.Sql("DELETE FROM movie WHERE Id = 92");
            migrationBuilder.Sql("DELETE FROM movie WHERE Id = 91");
            migrationBuilder.Sql("DELETE FROM movie WHERE Id = 90");
            migrationBuilder.Sql("DELETE FROM movie WHERE Id = 89");
            migrationBuilder.Sql("DELETE FROM movie WHERE Id = 88");
            migrationBuilder.Sql("DELETE FROM movie WHERE Id = 87");
            migrationBuilder.Sql("DELETE FROM movie WHERE Id = 86");
            migrationBuilder.Sql("DELETE FROM movie WHERE Id = 85");
            migrationBuilder.Sql("DELETE FROM movie WHERE Id = 84");
            migrationBuilder.Sql("DELETE FROM movie WHERE Id = 83");
            migrationBuilder.Sql("DELETE FROM movie WHERE Id = 82");
            migrationBuilder.Sql("DELETE FROM movie WHERE Id = 81");
            migrationBuilder.Sql("DELETE FROM movie WHERE Id = 80");
            migrationBuilder.Sql("DELETE FROM movie WHERE Id = 79");
            migrationBuilder.Sql("DELETE FROM movie WHERE Id = 78");
            migrationBuilder.Sql("DELETE FROM movie WHERE Id = 77");
            migrationBuilder.Sql("DELETE FROM movie WHERE Id = 76");
            migrationBuilder.Sql("DELETE FROM movie WHERE Id = 75");
            migrationBuilder.Sql("DELETE FROM movie WHERE Id = 74");
            migrationBuilder.Sql("DELETE FROM movie WHERE Id = 73");
            migrationBuilder.Sql("DELETE FROM movie WHERE Id = 72");
            migrationBuilder.Sql("DELETE FROM movie WHERE Id = 71");
            migrationBuilder.Sql("DELETE FROM movie WHERE Id = 70");
            migrationBuilder.Sql("DELETE FROM movie WHERE Id = 69");
            migrationBuilder.Sql("DELETE FROM movie WHERE Id = 68");
            migrationBuilder.Sql("DELETE FROM movie WHERE Id = 67");
            migrationBuilder.Sql("DELETE FROM movie WHERE Id = 66");
            migrationBuilder.Sql("DELETE FROM movie WHERE Id = 65");
            migrationBuilder.Sql("DELETE FROM movie WHERE Id = 64");
            migrationBuilder.Sql("DELETE FROM movie WHERE Id = 63");
            migrationBuilder.Sql("DELETE FROM movie WHERE Id = 62");
            migrationBuilder.Sql("DELETE FROM movie WHERE Id = 61");
            migrationBuilder.Sql("DELETE FROM movie WHERE Id = 60");
            migrationBuilder.Sql("DELETE FROM movie WHERE Id = 59");
            migrationBuilder.Sql("DELETE FROM movie WHERE Id = 58");
            migrationBuilder.Sql("DELETE FROM movie WHERE Id = 57");
            migrationBuilder.Sql("DELETE FROM movie WHERE Id = 56");
            migrationBuilder.Sql("DELETE FROM movie WHERE Id = 55");
            migrationBuilder.Sql("DELETE FROM movie WHERE Id = 54");
            migrationBuilder.Sql("DELETE FROM movie WHERE Id = 53");
            migrationBuilder.Sql("DELETE FROM movie WHERE Id = 52");
            migrationBuilder.Sql("DELETE FROM movie WHERE Id = 51");
            migrationBuilder.Sql("DELETE FROM movie WHERE Id = 50");
            migrationBuilder.Sql("DELETE FROM movie WHERE Id = 49");
            migrationBuilder.Sql("DELETE FROM movie WHERE Id = 48");
            migrationBuilder.Sql("DELETE FROM movie WHERE Id = 47");
            migrationBuilder.Sql("DELETE FROM movie WHERE Id = 46");
            migrationBuilder.Sql("DELETE FROM movie WHERE Id = 45");
            migrationBuilder.Sql("DELETE FROM movie WHERE Id = 44");
            migrationBuilder.Sql("DELETE FROM movie WHERE Id = 43");
            migrationBuilder.Sql("DELETE FROM movie WHERE Id = 42");
            migrationBuilder.Sql("DELETE FROM movie WHERE Id = 41");
            migrationBuilder.Sql("DELETE FROM movie WHERE Id = 40");
            migrationBuilder.Sql("DELETE FROM movie WHERE Id = 39");
            migrationBuilder.Sql("DELETE FROM movie WHERE Id = 38");
            migrationBuilder.Sql("DELETE FROM movie WHERE Id = 37");
            migrationBuilder.Sql("DELETE FROM movie WHERE Id = 36");
            migrationBuilder.Sql("DELETE FROM movie WHERE Id = 35");
            migrationBuilder.Sql("DELETE FROM movie WHERE Id = 34");
            migrationBuilder.Sql("DELETE FROM movie WHERE Id = 33");
            migrationBuilder.Sql("DELETE FROM movie WHERE Id = 32");
            migrationBuilder.Sql("DELETE FROM movie WHERE Id = 31");
            migrationBuilder.Sql("DELETE FROM movie WHERE Id = 30");
            migrationBuilder.Sql("DELETE FROM movie WHERE Id = 29");
            migrationBuilder.Sql("DELETE FROM movie WHERE Id = 28");
            migrationBuilder.Sql("DELETE FROM movie WHERE Id = 27");
            migrationBuilder.Sql("DELETE FROM movie WHERE Id = 26");
            migrationBuilder.Sql("DELETE FROM movie WHERE Id = 25");
            migrationBuilder.Sql("DELETE FROM movie WHERE Id = 24");
            migrationBuilder.Sql("DELETE FROM movie WHERE Id = 23");
            migrationBuilder.Sql("DELETE FROM movie WHERE Id = 22");
            migrationBuilder.Sql("DELETE FROM movie WHERE Id = 21");
            migrationBuilder.Sql("DELETE FROM movie WHERE Id = 20");
            migrationBuilder.Sql("DELETE FROM movie WHERE Id = 19");
            migrationBuilder.Sql("DELETE FROM movie WHERE Id = 18");
            migrationBuilder.Sql("DELETE FROM movie WHERE Id = 17");
            migrationBuilder.Sql("DELETE FROM movie WHERE Id = 16");
            migrationBuilder.Sql("DELETE FROM movie WHERE Id = 15");
            migrationBuilder.Sql("DELETE FROM movie WHERE Id = 14");
            migrationBuilder.Sql("DELETE FROM movie WHERE Id = 13");
            migrationBuilder.Sql("DELETE FROM movie WHERE Id = 12");
            migrationBuilder.Sql("DELETE FROM movie WHERE Id = 11");
            migrationBuilder.Sql("DELETE FROM movie WHERE Id = 10");
            migrationBuilder.Sql("DELETE FROM movie WHERE Id = 9");
            migrationBuilder.Sql("DELETE FROM movie WHERE Id = 8");
            migrationBuilder.Sql("DELETE FROM movie WHERE Id = 7");
            migrationBuilder.Sql("DELETE FROM movie WHERE Id = 6");
            migrationBuilder.Sql("DELETE FROM movie WHERE Id = 5");
            migrationBuilder.Sql("DELETE FROM movie WHERE Id = 4");
            migrationBuilder.Sql("DELETE FROM movie WHERE Id = 3");
            migrationBuilder.Sql("DELETE FROM movie WHERE Id = 2");
            migrationBuilder.Sql("DELETE FROM movie WHERE Id = 1");
        }
    }
}
